#!/bin/bash
# 19-shader.sh — compiles the conversion shader to SPIR-V and writes it as a
# C header (`src/vulkanvideo_rgb_nv12_spv.h`), which is KEPT in the
# repository: the product does not need the shader compiler, only whoever
# changes the shader does.
#
#   bash banchi/19-vulkan/19-shader.sh            (from the root of the tree)
#
# Needs `glslc` (package `glslc`, shaderc) or `glslangValidator`
# (`glslang-tools`); the server's devroot has both.
set -eu
ALBERO=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
SORGENTE=$ALBERO/src/vulkanvideo_rgb_nv12.comp
USCITA=$ALBERO/src/vulkanvideo_rgb_nv12_spv.h
if command -v glslc >/dev/null; then
	glslc -O --target-env=vulkan1.3 -fshader-stage=compute -mfmt=c -o "$USCITA.tmp" "$SORGENTE"
	{
		echo "/* generated by banchi/19-vulkan/19-shader.sh from src/vulkanvideo_rgb_nv12.comp: do not edit by hand */"
		# glslc writes `{0x..,0x..,}`: the braces are removed, so the header fits inside an initializer
		sed -e 's/^{//' -e 's/}$//' "$USCITA.tmp"
	} > "$USCITA"
	rm -f "$USCITA.tmp"
elif command -v glslangValidator >/dev/null; then
	glslangValidator -V --target-env vulkan1.3 -S comp -o "$USCITA.spv" "$SORGENTE"
	{
		echo "/* generated by banchi/19-vulkan/19-shader.sh from src/vulkanvideo_rgb_nv12.comp: do not edit by hand */"
		od -An -v -t x4 -w16 "$USCITA.spv" | sed 's/ \([0-9a-f]\{8\}\)/0x\1,/g'
	} > "$USCITA"
	rm -f "$USCITA.spv"
else
	echo "⛔ neither glslc nor glslangValidator" >&2
	exit 1
fi
echo "written $USCITA ($(wc -c < "$USCITA") bytes)"
