package interfaccia

import (
	"fmt"

	"remotix/installatore/motore"
)

// I testi delle schermate, nelle due lingue (DECISIONI §10.15), dal prototipo
// (grafica/installatore-prototipo/): parole comuni, «password», i dettagli tecnici a parte
// (fasi/17 §10, «Il linguaggio delle schermate»). Le chiavi mancanti escono come ⟨chiave⟩
// (TestTestiInterfaccia le trova).
var testi = map[string]due{
	"titolo.finestra":   {"REMOTIX — Installazione", "REMOTIX — Installation"},
	"intestazione":      {"Installazione", "Installation"},
	"passo.1":           {"Controllo", "Check"},
	"passo.2":           {"Scelte", "Choices"},
	"passo.3":           {"Piano", "Plan"},
	"passo.4":           {"Installazione", "Installation"},
	"passo.5":           {"Pronto", "Ready"},
	"passi.nota":        {"Fino al passo 3 non si tocca niente: solo lettura.", "Nothing is touched until step 3: read only."},
	"btn.annulla":       {"Annulla", "Cancel"},
	"btn.avanti":        {"Avanti", "Next"},
	"btn.indietro":      {"Indietro", "Back"},
	"btn.avanti_piano":  {"Avanti: il piano", "Next: the plan"},
	"btn.conferma":      {"Conferma e installa", "Confirm and install"},
	"btn.ferma":         {"Annulla e rimetti com'era", "Cancel and put it back as it was"},
	"btn.fermando":      {"Mi fermo dopo il passo in corso…", "Stopping after the current step…"},
	"btn.chiudi":        {"Chiudi", "Close"},
	"btn.registro":      {"Mostra il registro", "Show the log"},
	"btn.salva_rapp":    {"Salva il rapporto", "Save the report"},
	"btn.salva_piano":   {"Salva il piano come file", "Save the plan as a file"},
	"dettagli.mostra":   {"Mostra i dettagli tecnici", "Show the technical details"},
	"dettagli.nascondi": {"Nascondi i dettagli tecnici", "Hide the technical details"},
	"attendi.controllo": {"Controllo la macchina…", "Checking the machine…"},
	"attendi.piano":     {"Preparo il piano…", "Preparing the plan…"},
	"attendi.permessi":  {"Servono i permessi da amministratore: li chiedo al sistema.", "Administrator permissions are needed: I am asking the system."},
	"salvato":           {"Salvato in %s", "Saved in %s"},

	// 1 · il controllo
	"c.titolo":          {"Ho controllato questa macchina", "I checked this machine"},
	"c.sotto":           {"Niente è stato modificato. Ecco che cosa ho trovato.", "Nothing was changed. Here is what I found."},
	"c.ok.titolo":       {"REMOTIX si può installare", "REMOTIX can be installed"},
	"c.ok.testo":        {"Tutto quel che serve c'è, o lo sistemo io.", "Everything needed is here, or I will take care of it."},
	"c.cond1.titolo":    {"REMOTIX si può installare, a una condizione", "REMOTIX can be installed, on one condition"},
	"c.condN.titolo":    {"REMOTIX si può installare, a %d condizioni", "REMOTIX can be installed, on %d conditions"},
	"c.cond.video":      {"Per il video serve un componente che %s non include. Te lo chiedo al passo successivo.", "Video needs a component that %s does not include. I will ask you at the next step."},
	"c.cond.firewall":   {"Il firewall è acceso: per aprire la porta di REMOTIX ti chiedo il permesso al passo successivo.", "The firewall is on: I will ask your permission to open REMOTIX's port at the next step."},
	"c.cond.desktop":    {"Su questa macchina non c'è un desktop: te ne propongo uno al passo successivo.", "This machine has no desktop: I will suggest one at the next step."},
	"c.cond.altro":      {"Te la spiego al passo successivo.", "I will explain it at the next step."},
	"r.sistema":         {"Sistema", "System"},
	"r.desktop":         {"Desktop", "Desktop"},
	"r.scheda":          {"Scheda grafica", "Graphics card"},
	"r.video":           {"Video", "Video"},
	"r.accesso":         {"Accesso", "Sign-in"},
	"r.protezione":      {"Protezione del sistema", "System protection"},
	"r.firewall":        {"Firewall", "Firewall"},
	"r.porta":           {"Porta di collegamento", "Connection port"},
	"r.permessi":        {"Permessi", "Permissions"},
	"r.audio":           {"Audio", "Audio"},
	"s.ok":              {"A posto", "All set"},
	"s.consenso":        {"Serve il tuo consenso", "Needs your consent"},
	"s.scelta":          {"Serve la tua scelta", "Needs your choice"},
	"s.sistemo":         {"Lo sistemo io", "I will fix it"},
	"s.dopo":            {"Si prova dopo", "Tested later"},
	"s.male":            {"Non va", "Not OK"},
	"s.nonsi":           {"Non si sa", "Unknown"},
	"t.sistema.ok":      {"%s: REMOTIX è provato su questa versione", "%s: REMOTIX is tested on this version"},
	"t.sistema.fuori":   {"%s: non è fra le versioni provate, ma è compatibile", "%s: not among the tested versions, but compatible"},
	"t.desktop.ok":      {"%s: supportato", "%s: supported"},
	"t.desktop.nessuno": {"Nessun desktop supportato: te ne propongo uno", "No supported desktop: I will suggest one"},
	"t.scheda.ok":       {"%s: la userò per il video", "%s: I will use it for video"},
	"t.scheda.marca":    {"Scheda %s", "%s card"},
	"t.scheda.virtuale": {"Scheda grafica virtuale", "Virtual graphics card"},
	"t.scheda.generica": {"Scheda grafica", "Graphics card"},
	"t.scheda.nessuna":  {"Nessuna scheda: il video lo farà il processore", "No card: the processor will do the video"},
	"t.scheda.nvidia":   {"NVIDIA col driver proprietario: il video lo farà il processore", "NVIDIA with the proprietary driver: the processor will do the video"},
	"t.video.deposito":  {"Per trasmettere il video serve un componente che %s non include", "To send video a component is needed that %s does not include"},
	"t.video.ok":        {"La scheda sa trasmettere il video; lo provo alla fine", "The card can send video; I test it at the end"},
	"t.video.soft":      {"Il video lo farà il processore: funziona, ma è più lento", "The processor will do the video: it works, but it is slower"},
	"t.accesso.ok":      {"Si entrerà con nome e password di questa macchina", "People will sign in with this machine's name and password"},
	"t.accesso.male":    {"Il sistema d'accesso della distribuzione non si trova", "The distribution's sign-in system cannot be found"},
	"t.prot.selinux":    {"Attiva, e compatibile con REMOTIX", "Active, and compatible with REMOTIX"},
	"t.prot.apparmor":   {"Attiva, e compatibile con REMOTIX", "Active, and compatible with REMOTIX"},
	"t.prot.no":         {"Non attiva: REMOTIX non la richiede", "Not active: REMOTIX does not require it"},
	"t.fw.aperto":       {"Lascia già passare i collegamenti di REMOTIX", "Already lets REMOTIX connections through"},
	"t.fw.chiuso":       {"È acceso e non lascia ancora passare REMOTIX", "It is on and does not let REMOTIX through yet"},
	"t.fw.nessuno":      {"Non c'è un firewall acceso", "No firewall is on"},
	"t.fw.altro":        {"%s: non lo tocco, la porta va aperta a mano", "%s: I do not touch it, the port must be opened by hand"},
	"t.porta.libera":    {"La %d è libera", "Port %d is free"},
	"t.porta.occupata":  {"La %d è già usata da un altro programma", "Port %d is already used by another program"},
	"t.permessi.ok":     {"Tutti possono già usare la scheda grafica", "Everyone can already use the graphics card"},
	"t.permessi.uno":    {"A una persona manca il permesso di usare la scheda grafica", "One person lacks permission to use the graphics card"},
	"t.permessi.n":      {"A %d persone manca il permesso di usare la scheda grafica", "%d people lack permission to use the graphics card"},
	"t.audio":           {"C'è; si potrà provare solo al primo collegamento", "Present; it can only be tested at the first connection"},

	// 2 · le scelte
	"sc.titolo.1":     {"Una cosa da decidere", "One thing to decide"},
	"sc.titolo.2":     {"Due cose da decidere", "Two things to decide"},
	"sc.titolo.n":     {"%s cose da decidere", "%s things to decide"},
	"sc.sotto":        {"Tutto il resto ha un valore già scelto. Si cambia dopo, nella configurazione.", "Everything else already has a value. It can be changed later, in the configuration."},
	"sc.porta":        {"La porta su cui si collegano i browser", "The port browsers connect to"},
	"sc.porta.nota":   {"Di solito non serve cambiarla.", "Usually there is no need to change it."},
	"sc.porta.errata": {"Scrivi un numero fra 1 e 65535.", "Enter a number between 1 and 65535."},
	"sc.fw.aperto":    {"Il firewall la lascia già passare: non serve toccarlo.", "The firewall already lets it through: no need to touch it."},
	"sc.fw.nessuno":   {"Non c'è un firewall acceso: non serve toccarlo.", "No firewall is on: no need to touch it."},
	"sc.fw.altro":     {"Il firewall (%s) non lo tocco: la porta va aperta a mano.", "I do not touch the firewall (%s): the port must be opened by hand."},
	"sc.fw.titolo":    {"Il firewall", "The firewall"},
	"sc.fw.spiega":    {"Il firewall di questa macchina è acceso e blocca la porta. Per farci arrivare i browser va aperta, solo quella.", "This machine's firewall is on and blocks the port. For browsers to reach it, it must be opened — only that port."},
	"sc.fw.si":        {"Apri la porta nel firewall", "Open the port in the firewall"},
	"sc.fw.si.t":      {"I browser delle altre macchine potranno collegarsi.", "Browsers on other machines will be able to connect."},
	"sc.fw.no":        {"Non toccare il firewall", "Do not touch the firewall"},
	"sc.fw.no.t":      {"REMOTIX si installa, ma da fuori non si entra finché la porta non viene aperta a mano.", "REMOTIX is installed, but nobody gets in from outside until the port is opened by hand."},
	"sc.consigliato":  {"· consigliato", "· recommended"},
	"sc.video.titolo": {"Il componente per il video", "The video component"},
	"sc.video.spiega": {"Per ragioni di brevetti %s non include il componente che trasmette il video. Lo fornisce %s, una raccolta di programmi esterna a %s e molto usata. Lo aggiungo solo se lo decidi tu.", "For patent reasons %s does not include the component that sends video. %s provides it, a widely used collection of software outside %s. I add it only if you decide so."},
	"sc.video.si":     {"Aggiungi il componente da %s", "Add the component from %s"},
	"sc.video.si.t":   {"Immagine fluida, anche su schermi molto grandi.", "Smooth picture, even on very large screens."},
	"sc.video.no":     {"Non aggiungere niente", "Do not add anything"},
	"sc.video.no.t":   {"REMOTIX non si installa e la macchina resta com'è.", "REMOTIX is not installed and the machine stays as it is."},
	"sc.dep.titolo":   {"Una raccolta di programmi esterna: %s", "An external software collection: %s"},
	"sc.dep.spiega":   {"Il desktop che hai scelto ha bisogno di pezzi che %s non include: li fornisce %s. Lo aggiungo solo se lo decidi tu.", "The desktop you chose needs parts that %s does not include: %s provides them. I add it only if you decide so."},
	"sc.dep.si":       {"Aggiungi %s", "Add %s"},
	"sc.dep.no":       {"Non aggiungere niente", "Do not add anything"},
	"sc.dep.no.t":     {"Il piano ti dirà che cosa non si può fare senza.", "The plan will tell you what cannot be done without it."},
	"nd.titolo":       {"Su questa macchina non c'è un desktop", "This machine has no desktop"},
	"nd.sotto":        {"REMOTIX mostra un desktop nel browser: te ne installo uno dagli archivi di %s. Sarà visibile solo da remoto; davanti al monitor la macchina continuerà ad avviarsi senza grafica.", "REMOTIX shows a desktop in the browser: I will install one from %s's archives. It will be visible only remotely; at the monitor the machine will keep starting without graphics."},
	"nd.quale":        {"Quale desktop?", "Which desktop?"},
	"nd.gnome":        {"GNOME", "GNOME"},
	"nd.gnome.t":      {"Moderno e curato, il più usato", "Modern and polished, the most used"},
	"nd.kde":          {"KDE Plasma", "KDE Plasma"},
	"nd.kde.t":        {"Ricco di impostazioni, simile a Windows", "Full of settings, similar to Windows"},
	"nd.xfce":         {"XFCE", "XFCE"},
	"nd.xfce.t":       {"Leggero e tradizionale", "Light and traditional"},
	"nd.lxqt":         {"LXQt", "LXQt"},
	"nd.lxqt.t":       {"Il più leggero dei quattro", "The lightest of the four"},
	"nd.rif":          {"· quello di %s", "· %s's own"},
	"nd.no":           {"Non installare un desktop", "Do not install a desktop"},
	"nd.no.t":         {"Senza un desktop REMOTIX non ha niente da mostrare: non lo installo e la macchina resta com'è", "Without a desktop REMOTIX has nothing to show: I do not install it and the machine stays as it is"},
	"nd.nota":         {"Il desktop scelto arriva da %s stessa. Se un giorno togli REMOTIX, lo tolgo al meglio: qualche pacchetto trascinato può restare.", "The chosen desktop comes from %s itself. If you remove REMOTIX one day, I remove it as well as I can: some dragged-in packages may remain."},

	// 3 · il piano
	"p.titolo":          {"Ecco che cosa farò", "Here is what I will do"},
	"p.sotto":           {"Niente è stato ancora toccato. Se qualcosa va storto, annullo tutto quello che ho fatto io.", "Nothing has been touched yet. If something goes wrong, I undo everything I did."},
	"p.nota":            {"Prima di cominciare salvo la configurazione attuale. Il piano vale solo per questa macchina così com'è adesso.", "Before starting I save the current configuration. The plan is valid only for this machine as it is now."},
	"rev.tutto":         {"Si annulla del tutto", "Fully undone"},
	"rev.parte":         {"Si annulla in parte", "Partly undone"},
	"rev.no":            {"Non si annulla", "Cannot be undone"},
	"a.archivio":        {"Aggiungo l'archivio di REMOTIX e la sua chiave", "I add the REMOTIX archive and its key"},
	"a.archivio.t":      {"Da lì arriveranno anche gli aggiornamenti", "Updates will come from there too"},
	"a.archivio.f":      {"Aggiunto l'archivio di REMOTIX", "Added the REMOTIX archive"},
	"a.deposito":        {"Aggiungo %s", "I add %s"},
	"a.deposito.t":      {"Se un giorno lo tolgo, ciò che altri programmi usano resta", "If I remove it one day, what other programs use stays"},
	"a.deposito.f":      {"Aggiunto %s", "Added %s"},
	"a.acconsentito":    {"· hai acconsentito", "· you agreed"},
	"a.codec":           {"Metto il componente completo per il video", "I install the full video component"},
	"a.codec.t":         {"Quello di %s non sa trasmettere il video", "The %s one cannot send video"},
	"a.codec.f":         {"Componente completo per il video", "Full video component"},
	"a.desktop":         {"Installo il desktop %s", "I install the %s desktop"},
	"a.desktop.t":       {"Dagli archivi di %s; si vedrà solo da remoto", "From %s's archives; it will be seen only remotely"},
	"a.desktop.f":       {"Installato il desktop %s", "Installed the %s desktop"},
	"a.componenti":      {"Aggiungo i pezzi che servono al desktop", "I add the parts the desktop needs"},
	"a.componenti.t":    {"Piccoli programmi della distribuzione", "Small programs from the distribution"},
	"a.componenti.f":    {"Aggiunti i pezzi che servono al desktop", "Added the parts the desktop needs"},
	"a.pacchetti":       {"Installo REMOTIX e ciò che gli serve", "I install REMOTIX and what it needs"},
	"a.pacchetti.t":     {"Tutto controllato prima di cominciare", "Everything checked before starting"},
	"a.pacchetti.f":     {"REMOTIX installato", "REMOTIX installed"},
	"a.gruppi":          {"Do a %s il permesso di usare la scheda grafica", "I give %s permission to use the graphics card"},
	"a.gruppi.t":        {"Chi l'aveva già non viene toccato", "Whoever already had it is not touched"},
	"a.gruppi.f":        {"%s può usare la scheda grafica", "%s can use the graphics card"},
	"a.gruppi.fn":       {"%s possono usare la scheda grafica", "%s can use the graphics card"},
	"a.e":               {" e ", " and "},
	"a.cinture":         {"La macchina non si potrà spegnere né sospendere, da remoto e davanti al monitor; solo root può", "The machine cannot be shut down or suspended, remotely or at the monitor; only root can"},
	"a.cinture.t":       {"Protegge le sessioni di chi è collegato. Sempre attivo in REMOTIX", "It protects the sessions of whoever is connected. Always on in REMOTIX"},
	"a.cinture.f":       {"La macchina non si spegne né si sospende (solo root può)", "The machine cannot be shut down or suspended (only root can)"},
	"a.firewall":        {"Apro la porta %s nel firewall", "I open port %s in the firewall"},
	"a.firewall.t":      {"Solo quella, per i collegamenti di REMOTIX", "Only that one, for REMOTIX connections"},
	"a.firewall.f":      {"Porta %s aperta nel firewall", "Port %s opened in the firewall"},
	"a.servizio":        {"Accendo il servizio REMOTIX sulla porta %s", "I start the REMOTIX service on port %s"},
	"a.servizio.t":      {"Poi controllo che tutto funzioni davvero", "Then I check that everything really works"},
	"a.servizio.f":      {"REMOTIX acceso sulla porta %s", "REMOTIX running on port %s"},
	"a.aggiornamenti":   {"Accendo gli aggiornamenti automatici", "I turn on automatic updates"},
	"a.aggiornamenti.t": {"Le correzioni arrivano da sole, senza chiudere i desktop", "Fixes arrive by themselves, without closing desktops"},
	"a.aggiornamenti.f": {"Aggiornamenti automatici accesi", "Automatic updates on"},

	// 4 · l'avanzamento
	"av.titolo":       {"Sto installando", "Installing"},
	"av.sotto":        {"Se la macchina si spegne adesso, alla prossima apertura riprendo da dove ero, oppure annullo.", "If the machine shuts down now, next time I resume from where I was, or I undo."},
	"av.passo":        {"Passo %d di %d · %s", "Step %d of %d · %s"},
	"av.fiducia":      {"Motore e catalogo autentici (firma verificata)", "Engine and catalogue authentic (signature verified)"},
	"av.piano":        {"Il piano vale per questa macchina", "The plan is valid for this machine"},
	"av.verifica":     {"Controllo che tutto funzioni", "Checking that everything works"},
	"av.annullo":      {"Annullo quel che ho fatto", "Undoing what I did"},
	"av.inizio":       {"Comincio", "Starting"},
	"av.fine":         {"Fatto", "Done"},
	"av.annullamento": {"Sto rimettendo la macchina com'era", "Putting the machine back as it was"},
	"av.registro":     {"Il registro dell'operazione", "The operation log"},

	// 5 · pronto
	"pr.titolo":             {"REMOTIX è pronto", "REMOTIX is ready"},
	"pr.sotto":              {"Tutto funziona.", "Everything works."},
	"pr.sotto.dep":          {"Tutto funziona. Per il video usa un componente di %s, come hai scelto.", "Everything works. For video it uses a component from %s, as you chose."},
	"pr.sotto.cond":         {"Funziona, con una condizione: %s", "It works, with one condition: %s"},
	"cond.C-RIPIEGO":        {"il video lo fa il processore: funziona, ma è più lento", "the processor does the video: it works, but it is slower"},
	"cond.C-HARDWARE":       {"la scheda grafica non si può usare per il video", "the graphics card cannot be used for video"},
	"cond.C-DEPOSITO":       {"per il video serve un componente da un archivio esterno", "video needs a component from an external archive"},
	"cond.C-COMPONENTE":     {"ho aggiunto piccoli pezzi che servono al desktop", "I added small parts the desktop needs"},
	"cond.C-DESKTOP":        {"un desktop funziona con una limitazione (nei dettagli tecnici)", "a desktop works with a limitation (in the technical details)"},
	"cond.C-AMMINISTRATORE": {"la porta nel firewall va controllata a mano", "the port in the firewall must be checked by hand"},
	"cond.C-LIMITE":         {"un controllo non si è potuto fare fino in fondo (nei dettagli tecnici)", "one check could not be completed (in the technical details)"},
	"cond.altra":            {"una condizione, scritta nei dettagli tecnici", "a condition, written in the technical details"},
	"pr.apri":               {"Apri nel browser", "Open in the browser"},
	"pr.apri.t":             {"Chrome o Firefox. Il browser chiederà di accettare il certificato di questa macchina.", "Chrome or Firefox. The browser will ask you to accept this machine's certificate."},
	"pr.riconosci":          {"Come riconoscere questa macchina", "How to recognise this machine"},
	"pr.impronta":           {"Impronta del certificato:", "Certificate fingerprint:"},
	"pr.chi":                {"Chi può entrare", "Who can sign in"},
	"pr.chi.t":              {"Le persone che hanno un conto su questa macchina, con la loro password.", "People who have an account on this machine, with their password."},
	"pr.chi.root":           {"root è escluso.", "root is excluded."},
	"pr.chi.t2":             {"Ognuno ritrova il proprio desktop anche se chiude il browser.", "Everyone finds their own desktop again even after closing the browser."},
	"pr.cambiato":           {"Che cosa ho cambiato in questa macchina", "What I changed on this machine"},
	"pr.prove":              {"Le prove fatte", "The tests done"},
	"pr.riuscita":           {"Riuscita", "Passed"},
	"pr.fallita":            {"Non riuscita", "Failed"},
	"pr.nonsi":              {"Non si sa", "Unknown"},
	"pr.primo":              {"Al primo collegamento", "At the first connection"},
	"pr.k.servizio":         {"REMOTIX risponde ai collegamenti", "REMOTIX answers connections"},
	"pr.k.h264":             {"La scheda grafica trasmette il video", "The graphics card sends video"},
	"pr.k.h264soft":         {"Il video si trasmette (col processore)", "Video is sent (by the processor)"},
	"pr.k.pam":              {"L'accesso con nome e password è pronto", "Sign-in with name and password is ready"},
	"pr.k.porta":            {"Il firewall lascia passare la porta", "The firewall lets the port through"},
	"pr.k.passi":            {"Ogni passo del piano, ricontrollato (%d su %d)", "Every step of the plan, re-checked (%d of %d)"},
	"pr.k.audio":            {"L'audio", "Audio"},

	// esiti diversi da pronto
	"b.titolo.versione":   {"Questa versione di %s non è supportata", "This version of %s is not supported"},
	"b.titolo.distro":     {"Questa distribuzione non è supportata", "This distribution is not supported"},
	"b.titolo.fiducia":    {"Non posso fidarmi di questo installatore", "I cannot trust this installer"},
	"b.titolo.desktop":    {"Senza un desktop REMOTIX non si installa", "Without a desktop REMOTIX is not installed"},
	"b.titolo.fermo":      {"Mi sono fermato prima di toccare la macchina", "I stopped before touching the machine"},
	"b.titolo.annullata":  {"Ho rimesso la macchina com'era", "I put the machine back as it was"},
	"b.titolo.parte":      {"Non ho potuto rimettere tutto com'era", "I could not put everything back as it was"},
	"b.titolo.video":      {"Senza il componente per il video REMOTIX non si installa", "Without the video component REMOTIX is not installed"},
	"pr.router":           {"Da fuori della rete locale: inoltra sul router la porta %d, TCP e UDP, verso %s.", "From outside the local network: forward port %d, TCP and UDP, on the router to %s."},
	"b.titolo.permessi":   {"Senza i permessi da amministratore non posso continuare", "Without administrator permissions I cannot continue"},
	"b.titolo.interrotta": {"L'installazione si è interrotta", "The installation was interrupted"},
	"b.sotto.intatta":     {"Non ho toccato niente: la macchina è esattamente com'era.", "I did not touch anything: the machine is exactly as it was."},
	"b.sotto.annullata":   {"Quel che avevo fatto l'ho annullato, passo per passo.", "What I had done I undid, step by step."},
	"b.sotto.parte":       {"Quel che resta è scritto nel certificato; il registro dice ogni passo.", "What remains is written in the certificate; the log states every step."},
	"b.sotto.interrotta":  {"Alla prossima apertura riprendo da dove ero, oppure annullo.", "Next time I resume from where I was, or I undo."},
	"b.perche":            {"Perché", "Why"},
	"b.chefare":           {"Che cosa puoi fare", "What you can do"},
	"b.versioni":          {"Le versioni supportate sono elencate nel manuale.", "The supported versions are listed in the manual."},
	"b.serve":             {"Serve almeno %s.", "At least %s is needed."},
	"b.rilancia":          {"Rilancia l'installatore quando hai fatto.", "Launch the installer again when done."},
	"b.vecchia":           {"REMOTIX usa tecnologie di nuova generazione che %s non ha ancora: i suoi desktop sono troppo vecchi per essere comandati da remoto nel modo in cui lo fa REMOTIX.", "REMOTIX uses new-generation technologies that %s does not have yet: its desktops are too old to be driven remotely the way REMOTIX does."},
	"b.aggiorna":          {"Aggiorna la macchina a %s e riavvia l'installatore.", "Upgrade the machine to %s and restart the installer."},

	// la TUI
	"tui.tasti":    {"↑↓ scegli · spazio seleziona · invio avanti · esc indietro · q esci", "↑↓ choose · space select · enter next · esc back · q quit"},
	"tui.dettagli": {"d: dettagli tecnici", "d: technical details"},
	"tui.registro": {"r: registro", "r: log"},
	"tui.conferma": {"Invio per confermare e installare", "Enter to confirm and install"},
	"tui.ferma":    {"a: annulla e rimetti com'era", "a: cancel and put it back"},
	"tui.chiudi":   {"Invio per chiudere", "Enter to close"},
	"tui.porta":    {"Porta (scrivi il numero): ", "Port (type the number): "},
}

// due: un testo nelle due lingue.
type due struct{ it, en string }

func (t due) s() string {
	if motore.LinguaAttuale() == motore.IT || t.en == "" {
		return t.it
	}
	return t.en
}

// T: un testo dell'interfaccia nella lingua attuale.
func T(chiave string, args ...any) string {
	t, ok := testi[chiave]
	if !ok {
		return "⟨" + chiave + "⟩"
	}
	if len(args) == 0 {
		return t.s()
	}
	return fmt.Sprintf(t.s(), args...)
}
