package interfaccia

import "fmt"

// I testi delle schermate, in inglese (DECISIONI §10.35), dal prototipo
// (grafica/installatore-prototipo/): parole comuni, «password», i dettagli tecnici a parte
// (fasi/17 §10, «Il linguaggio delle schermate»). Le chiavi mancanti escono come ⟨chiave⟩
// (TestTestiInterfaccia le trova).
var testi = map[string]string{
	"titolo.finestra":   "REMOTIX — Installation",
	"intestazione":      "Installation",
	"passo.1":           "Check",
	"passo.2":           "Choices",
	"passo.3":           "Plan",
	"passo.4":           "Installation",
	"passo.5":           "Ready",
	"passi.nota":        "Nothing is touched until step 3: read only.",
	"btn.annulla":       "Cancel",
	"btn.avanti":        "Next",
	"btn.indietro":      "Back",
	"btn.avanti_piano":  "Next: the plan",
	"btn.conferma":      "Confirm and install",
	"btn.ferma":         "Cancel and put it back as it was",
	"btn.fermando":      "Stopping after the current step…",
	"btn.chiudi":        "Close",
	"btn.registro":      "Show the log",
	"btn.salva_rapp":    "Save the report",
	"btn.salva_piano":   "Save the plan as a file",
	"dettagli.mostra":   "Show the technical details",
	"dettagli.nascondi": "Hide the technical details",
	"attendi.controllo": "Checking the machine…",
	"attendi.piano":     "Preparing the plan…",
	"salvato":           "Saved in %s",

	// 1 · il controllo
	"c.titolo":          "I checked this machine",
	"c.sotto":           "Nothing was changed. Here is what I found.",
	"c.ok.titolo":       "REMOTIX can be installed",
	"c.ok.testo":        "Everything needed is here, or I will take care of it.",
	"c.cond1.titolo":    "REMOTIX can be installed, on one condition",
	"c.condN.titolo":    "REMOTIX can be installed, on %d conditions",
	"c.cond.video":      "Video needs a component that %s does not include. I will ask you at the next step.",
	"c.cond.firewall":   "The firewall is on: I will ask your permission to open REMOTIX's port at the next step.",
	"c.cond.desktop":    "This machine has no desktop: I will suggest one at the next step.",
	"c.cond.altro":      "I will explain it at the next step.",
	"r.sistema":         "System",
	"r.desktop":         "Desktop",
	"r.scheda":          "Graphics card",
	"r.video":           "Video",
	"r.accesso":         "Sign-in",
	"r.protezione":      "System protection",
	"r.firewall":        "Firewall",
	"r.porta":           "Connection port",
	"r.permessi":        "Permissions",
	"r.audio":           "Audio",
	"s.ok":              "All set",
	"s.consenso":        "Needs your consent",
	"s.scelta":          "Needs your choice",
	"s.sistemo":         "I will fix it",
	"s.dopo":            "Tested later",
	"s.male":            "Not OK",
	"s.nonsi":           "Unknown",
	"t.sistema.ok":      "%s: REMOTIX is tested on this version",
	"t.sistema.fuori":   "%s: not among the tested versions, but compatible",
	"t.desktop.ok":      "%s: supported",
	"t.desktop.nessuno": "No supported desktop: I will suggest one",
	"t.scheda.ok":       "%s: I will use it for video",
	"t.scheda.marca":    "%s card",
	"t.scheda.virtuale": "Virtual graphics card",
	"t.scheda.generica": "Graphics card",
	"t.scheda.nessuna":  "No card: without one, REMOTIX does not send video",
	"t.scheda.nvidia":   "NVIDIA with the proprietary driver: I will use the other card for video",
	"t.video.deposito":  "To send video a component is needed that %s does not include",
	"t.video.ok":        "The card can send video; I test it at the end",
	"t.accesso.ok":      "People will sign in with this machine's name and password",
	"t.accesso.male":    "The distribution's sign-in system cannot be found",
	"t.prot.selinux":    "Active, and compatible with REMOTIX",
	"t.prot.apparmor":   "Active, and compatible with REMOTIX",
	"t.prot.no":         "Not active: REMOTIX does not require it",
	"t.fw.aperto":       "Already lets REMOTIX connections through",
	"t.fw.chiuso":       "It is on and does not let REMOTIX through yet",
	"t.fw.nessuno":      "No firewall is on",
	"t.fw.altro":        "%s: I do not touch it, the port must be opened by hand",
	"t.porta.libera":    "Port %d is free",
	"t.porta.occupata":  "Port %d is already used by another program",
	"t.permessi.ok":     "Everyone can already use the graphics card",
	"t.permessi.uno":    "One person lacks permission to use the graphics card",
	"t.permessi.n":      "%d people lack permission to use the graphics card",
	"t.audio":           "Present; it can only be tested at the first connection",

	// 2 · le scelte
	"sc.titolo.1":     "One thing to decide",
	"sc.titolo.2":     "Two things to decide",
	"sc.titolo.n":     "%s things to decide",
	"sc.sotto":        "Everything else already has a value. It can be changed later, in the configuration.",
	"sc.porta":        "The port browsers connect to",
	"sc.porta.nota":   "Usually there is no need to change it.",
	"sc.porta.errata": "Enter a number between 1 and 65535.",
	"sc.fw.aperto":    "The firewall already lets it through: no need to touch it.",
	"sc.fw.nessuno":   "No firewall is on: no need to touch it.",
	"sc.fw.altro":     "I do not touch the firewall (%s): the port must be opened by hand.",
	"sc.fw.titolo":    "The firewall",
	"sc.fw.spiega":    "This machine's firewall is on and blocks the port. For browsers to reach it, it must be opened — only that port.",
	"sc.fw.si":        "Open the port in the firewall",
	"sc.fw.si.t":      "Browsers on other machines will be able to connect.",
	"sc.fw.no":        "Do not touch the firewall",
	"sc.fw.no.t":      "REMOTIX is installed, but nobody gets in from outside until the port is opened by hand.",
	"sc.consigliato":  "· recommended",
	"sc.video.titolo": "The video component",
	"sc.video.spiega": "For patent reasons %s does not include the component that sends video. %s provides it, a widely used collection of software outside %s. I add it only if you decide so.",
	"sc.video.si":     "Add the component from %s",
	"sc.video.si.t":   "Smooth picture, even on very large screens.",
	"sc.video.no":     "Do not add anything",
	"sc.video.no.t":   "REMOTIX is not installed and the machine stays as it is.",
	"sc.dep.titolo":   "An external software collection: %s",
	"sc.dep.spiega":   "The desktop you chose needs parts that %s does not include: %s provides them. I add it only if you decide so.",
	"sc.dep.si":       "Add %s",
	"sc.dep.no":       "Do not add anything",
	"sc.dep.no.t":     "The plan will tell you what cannot be done without it.",
	"nd.titolo":       "This machine has no desktop",
	"nd.sotto":        "REMOTIX shows a desktop in the browser: I will install one from %s's archives. It will be visible only remotely; at the monitor the machine will keep starting without graphics.",
	"nd.quale":        "Which desktop?",
	"nd.gnome":        "GNOME",
	"nd.gnome.t":      "Modern and polished, the most used",
	"nd.kde":          "KDE Plasma",
	"nd.kde.t":        "Full of settings, similar to Windows",
	"nd.xfce":         "XFCE",
	"nd.xfce.t":       "Light and traditional",
	"nd.lxqt":         "LXQt",
	"nd.lxqt.t":       "The lightest of the four",
	"nd.rif":          "· %s's own",
	"nd.no":           "Do not install a desktop",
	"nd.no.t":         "Without a desktop REMOTIX has nothing to show: I do not install it and the machine stays as it is",
	"nd.nota":         "The chosen desktop comes from %s itself. If you remove REMOTIX one day, I remove it as well as I can: some dragged-in packages may remain.",

	// 3 · il piano
	"p.titolo":       "Here is what I will do",
	"p.sotto":        "Nothing has been touched yet. If something goes wrong, I undo everything I did.",
	"p.nota":         "Before starting I save the current configuration. The plan is valid only for this machine as it is now.",
	"rev.tutto":      "Fully undone",
	"rev.parte":      "Partly undone",
	"rev.no":         "Cannot be undone",
	"a.archivio":     "I add the REMOTIX archive and its key",
	"a.archivio.t":   "Updates will come from there too, with the system's",
	"a.archivio.f":   "Added the REMOTIX archive",
	"a.deposito":     "I add %s",
	"a.deposito.t":   "If I remove it one day, what other programs use stays",
	"a.deposito.f":   "Added %s",
	"a.acconsentito": "· you agreed",
	"a.codec":        "I install the full graphics card driver",
	"a.codec.t":      "The %s one cannot encode video on the card",
	"a.codec.f":      "Full graphics card driver",
	"a.desktop":      "I install the %s desktop",
	"a.desktop.t":    "From %s's archives; it will be seen only remotely",
	"a.desktop.f":    "Installed the %s desktop",
	"a.componenti":   "I add the parts the desktop needs",
	"a.componenti.t": "Small programs from the distribution",
	"a.componenti.f": "Added the parts the desktop needs",
	"a.pacchetti":    "I install REMOTIX and what it needs",
	"a.pacchetti.t":  "Everything checked before starting",
	"a.pacchetti.f":  "REMOTIX installed",
	"a.gruppi":       "I give %s permission to use the graphics card",
	"a.gruppi.t":     "Whoever already had it is not touched",
	"a.gruppi.f":     "%s can use the graphics card",
	"a.gruppi.fn":    "%s can use the graphics card",
	"a.e":            " and ",
	"a.cinture":      "The machine cannot be shut down or suspended, remotely or at the monitor; only root can",
	"a.cinture.t":    "It protects the sessions of whoever is connected. Always on in REMOTIX",
	"a.cinture.f":    "The machine cannot be shut down or suspended (only root can)",
	"a.firewall":     "I open port %s in the firewall",
	"a.firewall.t":   "Only that one, for REMOTIX connections",
	"a.firewall.f":   "Port %s opened in the firewall",
	"a.servizio":     "I start the REMOTIX service on port %s",
	"a.servizio.t":   "Then I check that everything really works",
	"a.servizio.f":   "REMOTIX running on port %s",

	// 4 · l'avanzamento
	"av.titolo":       "Installing",
	"av.sotto":        "If the machine shuts down now, next time I resume from where I was, or I undo.",
	"av.passo":        "Step %d of %d · %s",
	"av.fiducia":      "The engine's catalogue can be read",
	"av.piano":        "The plan is valid for this machine",
	"av.verifica":     "Checking that everything works",
	"av.annullo":      "Undoing what I did",
	"av.inizio":       "Starting",
	"av.fine":         "Done",
	"av.annullamento": "Putting the machine back as it was",
	"av.registro":     "The operation log",

	// 5 · pronto
	"pr.titolo":             "REMOTIX is ready",
	"pr.sotto":              "Everything works.",
	"pr.sotto.dep":          "Everything works. For video it uses a component from %s, as you chose.",
	"pr.sotto.cond":         "It works, with one condition: %s",
	"cond.C-HARDWARE":       "the graphics card cannot be used for video",
	"cond.C-DEPOSITO":       "video needs a component from an external archive",
	"cond.C-COMPONENTE":     "I added small parts the desktop needs",
	"cond.C-DESKTOP":        "a desktop works with a limitation (in the technical details)",
	"cond.C-AMMINISTRATORE": "the port in the firewall must be checked by hand",
	"cond.C-LIMITE":         "one check could not be completed (in the technical details)",
	"cond.altra":            "a condition, written in the technical details",
	"pr.apri":               "Open in the browser",
	"pr.apri.t":             "Chrome or Firefox. The browser will ask you to accept this machine's certificate.",
	"pr.riconosci":          "How to recognise this machine",
	"pr.impronta":           "Certificate fingerprint:",
	"pr.chi":                "Who can sign in",
	"pr.chi.t":              "People who have an account on this machine, with their password.",
	"pr.chi.root":           "root is excluded.",
	"pr.chi.t2":             "Everyone finds their own desktop again even after closing the browser.",
	"pr.cambiato":           "What I changed on this machine",
	"pr.prove":              "The tests done",
	"pr.riuscita":           "Passed",
	"pr.fallita":            "Failed",
	"pr.nonsi":              "Unknown",
	"pr.primo":              "At the first connection",
	"pr.k.servizio":         "REMOTIX answers connections",
	"pr.k.h264":             "The graphics card sends video",
	"pr.k.pam":              "Sign-in with name and password is ready",
	"pr.k.porta":            "The firewall lets the port through",
	"pr.k.passi":            "Every step of the plan, re-checked (%d of %d)",
	"pr.k.audio":            "Audio",

	// esiti diversi da pronto
	"b.titolo.versione":   "This version of %s is not supported",
	"b.titolo.distro":     "This distribution is not supported",
	"b.titolo.scheda":     "Without a card that encodes video REMOTIX is not installed",
	"b.titolo.fiducia":    "I cannot trust this installer",
	"b.titolo.desktop":    "Without a desktop REMOTIX is not installed",
	"b.titolo.fermo":      "I stopped before touching the machine",
	"b.titolo.annullata":  "I put the machine back as it was",
	"b.titolo.parte":      "I could not put everything back as it was",
	"b.titolo.video":      "Without the video component REMOTIX is not installed",
	"pr.router":           "From outside the local network: forward port %d, TCP and UDP, on the router to %s.",
	"b.titolo.interrotta": "The installation was interrupted",
	"b.sotto.intatta":     "I did not touch anything: the machine is exactly as it was.",
	"b.sotto.annullata":   "What I had done I undid, step by step.",
	"b.sotto.parte":       "What remains is written in the certificate; the log states every step.",
	"b.sotto.interrotta":  "Next time I resume from where I was, or I undo.",
	"b.perche":            "Why",
	"b.chefare":           "What you can do",
	"b.versioni":          "The supported versions are listed in the manual.",
	"b.serve":             "At least %s is needed.",
	"b.rilancia":          "Launch the installer again when done.",
	"b.vecchia":           "REMOTIX uses new-generation technologies that %s does not have yet: its desktops are too old to be driven remotely the way REMOTIX does.",
	"b.aggiorna":          "Upgrade the machine to %s and restart the installer.",

	// la TUI
	"tui.tasti":    "↑↓ choose · space select · enter next · esc back · q quit",
	"tui.dettagli": "d: technical details",
	"tui.registro": "r: log",
	"tui.conferma": "Enter to confirm and install",
	"tui.ferma":    "a: cancel and put it back",
	"tui.chiudi":   "Enter to close",
	"tui.porta":    "Port (type the number): ",
}

// T: un testo dell'interfaccia.
func T(chiave string, args ...any) string {
	t, ok := testi[chiave]
	if !ok {
		return "⟨" + chiave + "⟩"
	}
	if len(args) == 0 {
		return t
	}
	return fmt.Sprintf(t, args...)
}
