#!/bin/bash
# resto.sh — the things that remain: rotation, administrator's certificate,
#            ban + page + unban.  Inside the container.
set -uo pipefail
D=/srv/src/remotix
IND=192.168.0.2
PORTA=${1:-7448}
ok() { printf '    OK  %s\n' "$*"; }
ko() { printf '    NO  %s\n' "$*"; }
log(){ printf '\n== %s\n' "$*"; }

# ---------------------------------------------------------------------------
# ⛔ THE PASSWORD NO LONGER GOES THROUGH THE COMMAND LINE — defect **D12**,
#    cured on 12 Aug 2026.  `python3` is a PROCESS: the password sat in its
#    `argv`, that is in `/proc/<pid>/cmdline`, readable by anyone.
#
# ⭐ The way is the one already in the house (`banchi/01-b10-lancia.sh`): a `0600`
#    file written with `printf` — a **builtin**, so not even the write goes
#    through a process with the password in `argv` — passed as `--parola-file`,
#    and deleted with a `trap`.  What ends up in `cmdline` is the PATH.
#
# ⚠ The WRONG passwords stay where they are: they are nobody's secret, and two
#   ways for the same thing would be form **E2**.  Here, though, they buy
#   something — the scene is "three failed attempts" — so they are declared.
PAROLA=${PAROLA:-parola-di-prova}
PAROLA_FILE=/srv/src/tmp/prodotto-resto-parola

ripulisci_parola() { rm -f "$PAROLA_FILE"; }
trap ripulisci_parola EXIT

# ⛔ `umask` IN A SUBSHELL: bare, it would stick to everything that follows.
mkdir -p /srv/src/tmp \
  && ( umask 077; : > "$PAROLA_FILE" ) \
  && chmod 600 "$PAROLA_FILE" \
  || { ko "⛔ cannot write $PAROLA_FILE"; exit 2; }
printf '%s\n' "$PAROLA" > "$PAROLA_FILE"

accendi() # $1 = certificates dir, $2 = ban file, $3 = log
{
  nohup "$D/remotix" --indirizzo 0.0.0.0 --nome "$IND" --porta "$PORTA" \
    --certificati "$1" --pagina "$D/pagina.html" --ban "$2" >"$3" 2>&1 &
  PID=$!
  sleep 2
  [ -d "/proc/$PID" ]
}
spegni() { kill -TERM "$PID" 2>/dev/null; sleep 1; [ -d "/proc/$PID" ] && kill -KILL "$PID"; return 0; }

# ---------------------------------------------------------------------------
log "1. THE ROTATION — a session certificate with less than 2 days left"
C=/srv/src/cert-rot
rm -rf $C; mkdir -p $C
# the long-lived one, ours
openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
  -keyout $C/pagina.key -out $C/pagina.pem -days 365 -nodes -subj "/CN=$IND" \
  -addext "subjectAltName=IP:$IND" >/dev/null 2>&1 && echo "generated by REMOTIX" > $C/pagina.nostro
# the short one, at ONE day: below the margin of 2
openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
  -keyout $C/sessione.key -out $C/sessione.pem -days 1 -nodes -subj "/CN=$IND" \
  -addext "subjectAltName=IP:$IND" >/dev/null 2>&1 && echo "generated by REMOTIX" > $C/sessione.nostro
chmod 600 $C/*.key
VECCHIA=$(openssl x509 -in $C/sessione.pem -outform der | openssl dgst -sha256 -binary | base64 -w0)
echo "    fingerprint BEFORE: $VECCHIA"

accendi $C /srv/src/ban-rot /srv/src/rot.log || { ko "dead"; cat /srv/src/rot.log; exit 2; }
NUOVA=$(openssl x509 -in $C/sessione.pem -outform der | openssl dgst -sha256 -binary | base64 -w0)
echo "    fingerprint AFTER:  $NUOVA"
[ "$VECCHIA" != "$NUOVA" ] && ok "the session certificate WAS rotated at startup" || ko "NOT rotated"
GIORNI=$(( ( $(date -d "$(openssl x509 -in $C/sessione.pem -noout -enddate | cut -d= -f2)" +%s) - $(date +%s) ) / 86400 ))
[ "$GIORNI" -le 14 ] && [ "$GIORNI" -ge 10 ] && ok "the new one expires in $GIORNI days (ceiling 14)" || ko "expires in $GIORNI days"
curl -sk "https://$IND:$PORTA/impronta" | grep -F -q "$NUOVA" && ok "/impronta serves the NEW one" || ko "/impronta serves an old fingerprint"
curl -sk "https://$IND:$PORTA/" | grep -F -q "$NUOVA" && ok "the page carries the NEW one" || ko "the page carries an old fingerprint"
grep -a -F -q "rotation of the SESSION certificate" /srv/src/rot.log && ok "and it says so in the log" || ko "the log is silent about the rotation"
spegni

# ---------------------------------------------------------------------------
log "2. THE ADMINISTRATOR'S CERTIFICATE is not regenerated (RCP.md 4.1, B13.3)"
rm -f $C/pagina.nostro           # marker gone: now «it is not ours»
IMP=$(openssl x509 -in $C/pagina.pem -outform der | openssl dgst -sha256 -binary | base64 -w0)
accendi $C /srv/src/ban-rot /srv/src/adm.log || { ko "dead"; cat /srv/src/adm.log; exit 2; }
DOPO=$(openssl x509 -in $C/pagina.pem -outform der | openssl dgst -sha256 -binary | base64 -w0)
[ "$IMP" = "$DOPO" ] && ok "the page certificate was NOT touched" || ko "it was REGENERATED: violates §4.1"
grep -a -F -q "is not ours" /srv/src/adm.log && ok "and it declares it in the log" || ko "the log does not say so"
spegni

# ---------------------------------------------------------------------------
log "3. THE BAN — three failed authentications, then the page SAYS so (SPECIFICHE 4.2)"
rm -rf /srv/src/cert-ban /srv/src/ban-prova; mkdir -p /srv/src/cert-ban
accendi /srv/src/cert-ban /srv/src/ban-prova /srv/src/ban.log || { ko "dead"; cat /srv/src/ban.log; exit 2; }
for i in 1 2 3; do
  timeout 30 python3 /srv/src/01-b3-cliente.py --indirizzo "$IND" --porta "$PORTA" \
    --utente prova --parola SBAGLIATA-$i >/dev/null 2>&1
  echo "    attempt $i: exit $?"
done
log "   the fourth, and the page"
timeout 30 python3 /srv/src/01-b3-cliente.py --indirizzo "$IND" --porta "$PORTA" \
  --utente prova --parola-file "$PAROLA_FILE" 2>&1 | tail -4
curl -sk "https://$IND:$PORTA/" -o /srv/src/pagina-ban.html
if grep -a -F -q "tentativi di accesso da questo indirizzo sono esauriti" /srv/src/pagina-ban.html; then
  ok "⭐ the page LOADS and says the attempts are exhausted"
else
  ko "the page does not say so"
  grep -a -o 'AVVISO = "[^"]*"' /srv/src/pagina-ban.html | head -1
fi
echo "    -- the ban file:"
cat /srv/src/ban-prova 2>&1 | sed 's/^/        /'
spegni

log "   and the UNBAN (SPECIFICHE 4.2: the other way out)"
"$D/remotix" --ban /srv/src/ban-prova --sblocca "$IND" --nome "$IND" 2>&1 | sed 's/^/    /'
echo "    exit: $?"
echo "    -- the ban file after the unban:"
cat /srv/src/ban-prova 2>&1 | sed 's/^/        /'

log "   and the page goes back to normal"
accendi /srv/src/cert-ban /srv/src/ban-prova /srv/src/ban2.log || { ko "dead"; exit 2; }
curl -sk "https://$IND:$PORTA/" -o /srv/src/pagina-dopo.html
grep -a -F -q "tentativi di accesso da questo indirizzo sono esauriti" /srv/src/pagina-dopo.html \
  && ko "the notice is still there" || ok "the notice is gone"
timeout 30 python3 /srv/src/01-b3-cliente.py --indirizzo "$IND" --porta "$PORTA" \
  --utente prova --parola-file "$PAROLA_FILE" 2>&1 | tail -3
spegni
