/*
 * certificati.h — ⛔ THE TWO CERTIFICATES, AND THEY ARE TWO (`RCP.md` §4.1-bis).
 *
 * ---------------------------------------------------------------------------
 * ⛔ WHY TWO, AND WHAT CONFUSING THEM COSTS
 *
 *   the LONG-LIVED  serves the PAGE, over TCP.  It is the one on which the user
 *                   grants the exception the first time on every device, so ⛔ it
 *                   must NOT change more often than necessary.
 *
 *   the SHORT       serves the WebTransport SESSION.  The browser does not look at
 *                   the exception on that connection — it looks at the fingerprint
 *                   the page passes to it (`serverCertificateHashes`) — and on that
 *                   road it demands a certificate valid for LESS THAN 14 DAYS [S].
 *                   So it rotates, and rotates on its own.
 *
 * ⚠ Whoever makes only one passes every bench and makes the warning reappear every
 *   two weeks, «and nobody would connect the two things» (§4.1-bis).  It is the
 *   defect that B13.1 exists to see, and the way not to commit it is for the two
 *   to have two different names right down to here.
 *
 * ---------------------------------------------------------------------------
 * ⛔ THE ADMINISTRATOR'S CERTIFICATE IS NOT TOUCHED
 *
 * `RCP.md` §4.1: «if the administrator installs one issued by an authority, the
 * server MUST use it and MUST NOT regenerate its own».  The way to know it
 * without guessing: every certificate generated BY US carries a marker file
 * next to it (`.nostro`).  ⛔ A `pagina.pem` without a marker belongs to someone
 * else, and is never regenerated — not even when it expires.
 *
 * ⚠ The criterion is «did we write it?», not «is it self-signed?»: the second
 *   is a deduction (form E1), and would be wrong on a self-signed private CA.
 */
#ifndef REMOTIX_CERTIFICATI_H
#define REMOTIX_CERTIFICATI_H

#include <stdbool.h>
#include <time.h>

/* The days, and where they come from. */
#define CERT_GIORNI_PAGINA 365 /* long-lived: the user's exception lasts */
#define CERT_GIORNI_SESSIONE 13 /* ⛔ below the ceiling of 14 of §4.1-bis */
#define CERT_MARGINE_GIORNI 2 /* rotate WHEN this many REMAIN, not at expiry */

typedef struct {
	char dir[256];
	char indirizzo[128];

	char pagina_pem[320], pagina_key[320], pagina_marca[320];
	char sessione_pem[320], sessione_key[320], sessione_marca[320];

	/* The SHA-256 fingerprint of the DER of the SESSION certificate, in base64:
	 * ⛔ of the certificate, not of the public key (finding R1.14 of
	 * `RCP.md`) — whoever published the key's one got a comparison that
	 * never matches, and the symptom was «WebTransport does not connect»
	 * without any error naming the fingerprint. */
	char impronta[64];
	/* The same in hexadecimal, which is the form of the logs and of the
	 * browsers' error messages. */
	char impronta_esa[80];
	time_t sessione_scade;
	/* ⛔ How many times the session certificate has been rotated since the
	 *    server started.  It is the denominator of B13.1: without it «it
	 *    rotated» and «it was never tried» look the same. */
	unsigned rotazioni;
	bool pagina_e_nostro;
} certificati;

/* Prepares the two certificates: reads them if they exist and are valid,
 * generates them otherwise.  Returns false only if no usable one can be had. */
bool certificati_prepara(certificati *c, const char *dir, const char *indirizzo);

/* ⛔ Rotates the SESSION certificate before it expires, not after: if fewer
 * than `CERT_MARGINE_GIORNI` remain a new one is made and the fingerprint is
 * recomputed.  Returns true if it rotated — the host must rebuild the TLS context.
 *
 * ⚠ The page certificate does NOT rotate here: it is long-lived on purpose. */
bool certificati_ruota_se_serve(certificati *c);

#endif
