package motore

// codiciInglese: the English texts of the RX-… codes (same codes, same meaning: codici.go).
// [0] = text, [1] = remedy.
var codiciInglese = map[string][2]string{
	"RX-TRUST-001": {"(retired in T8) The catalogue signature could not be verified yet: the engine proceeded only with --senza-firma.", ""},
	"RX-TRUST-002": {"The catalogue of supported combinations has expired.", "Download the updated engine or catalogue."},
	"RX-TRUST-003": {"The catalogue requires a newer engine than this one.", "Download the updated engine."},
	"RX-TRUST-004": {"The catalogue cannot be read or has an unknown format.", "Download the engine or the catalogue again."},
	"RX-TRUST-005": {"(retired in T8) Trust in the catalogue was not verified and proceeding anyway was not requested.", ""},
	"RX-TRUST-006": {"The catalogue (or the engine) has no signature, or the signature cannot be read: nothing proceeds without a signature.", "Download the catalogue again with its .firma file next to it, or give a signed offline catalogue (--catalogo FILE, with FILE.firma)."},
	"RX-TRUST-007": {"The signature does not match: the catalogue (or the engine) was altered, or the signature is for something else.", "Do not use this file: download it again from REMOTIX and check where it comes from."},
	"RX-TRUST-008": {"The signing key is not certified by the REMOTIX root key written in the engine.", "Do not use this file: it does not come from REMOTIX, or the engine is too old for the new key."},
	"RX-TRUST-009": {"The signing key has expired (or is not valid yet).", "Download the updated catalogue, signed with the current key; also check the machine's clock."},
	"RX-TRUST-010": {"The signing key was REVOKED by REMOTIX.", "Download the catalogue signed with the new key; do not use anything signed with the revoked one."},
	"RX-TRUST-011": {"The catalogue received is older than one already verified on this machine: the most recent is kept.", "If it was given by hand, give a more recent one; if it comes from the archive, the mirror may be behind."},
	"RX-TRUST-012": {"The list of revoked keys is not signed by the root key, or it was altered.", "Nothing proceeds until the list verifies: download it again from REMOTIX."},
	"RX-TRUST-013": {"The updated catalogue could not be downloaded from the archive: the most recent one already verified is used.", "Check the network; the check is repeated at the next run."},
	"RX-TRUST-014": {"The running engine does not match its signature.", "Do not use this engine: reinstall it from the REMOTIX archive."},
	"RX-TRUST-015": {"The engine has no signature next to it: its authenticity was verified by whoever downloaded it (the entry script) or by the package manager (chain B).", ""},
	"RX-TRUST-016": {"The offline catalogue given is older than one already verified on this machine.", "Give the most recent catalogue."},

	"RX-DISTRO-001":  {"Cannot tell which distribution is installed (/etc/os-release is missing or unreadable).", ""},
	"RX-SYSTEMD-001": {"The machine was not booted with systemd: REMOTIX uses logind and the systemd user manager.", "REMOTIX does not run without systemd."},
	"RX-GPU-001":     {"There is no graphics card with a render node (/dev/dri/renderD*): encoding will be in software.", "If the machine has a card, check that its driver is loaded."},
	"RX-GPU-002":     {"The NVIDIA card uses the proprietary driver: it does not encode H.264 through VA-API.", "Encoding will use the software fallback (condition C-HARDWARE)."},
	"RX-H264-001":    {"Whether the card encodes H.264 is not known yet: the check launches no programs, and the one-frame test runs after installation (7a), with the REMOTIX binary.", "The check stays UNKNOWN until then: it does not count as «fine»."},
	"RX-H264-002":    {"The card did not encode the H.264 test frame.", "Check the card's VA-API driver."},
	"RX-H264-003":    {"The card does not encode H.264: on Fedora and the RHEL family RPM Fusion is needed.", "The command is in the compatibility report (condition C-DEPOSITO, decision D5)."},
	"RX-H264-004":    {"The card does not encode H.264: on openSUSE Packman is needed.", "The command is in the compatibility report (condition C-DEPOSITO, decision D5)."},
	"RX-H264-005":    {"Not even the software fallback (libx264) is in this machine's ffmpeg.", ""},
	"RX-PAM-001":     {"The distribution's login stack cannot be found.", "Check the files in /etc/pam.d (or /usr/lib/pam.d on openSUSE)."},
	"RX-PAM-002":     {"The distribution's login stack contains pam_faillock: three wrong passwords lock the account, even at the machine.", "Decision D3, open."},
	"RX-PAM-003":     {"A «remotix» login file already exists.", ""},
	"RX-PAM-004":     {"The pam_systemd module cannot be found: without it the desktop does not start.", ""},
	"RX-SELINUX-001": {"SELinux is active and enforcing.", "REMOTIX behaviour under SELinux is stage T6."},
	"RX-FW-001":      {"The firewall is on and the REMOTIX port is not open in it.", "Open it (decision D6: the engine can do it, with consent)."},
	"RX-FW-002":      {"The firewall state for the REMOTIX port could not be read.", "Reading the ufw and nftables rules requires root."},
	"RX-FW-003":      {"The REMOTIX port is already taken by another program.", "Choose another port or stop that program."},
	"RX-FW-004":      {"This engine can open the port only with firewalld: ufw and nftables are not done yet.", "Open the port by hand, with the given command."},
	"RX-FW-005":      {"From this machine it cannot be known whether the port is reachable from the network (routers, external firewalls).", ""},
	"RX-LOGIND-001":  {"logind kills the processes of users who log out (KillUserProcesses=yes): a REMOTIX desktop might die.", "Effect to be measured; declared for now."},
	"RX-LOGIND-002":  {"The KillUserProcesses value could not be read from logind.", ""},
	"RX-GRUPPI-001":  {"The «render» group does not exist on this machine.", ""},
	"RX-GRUPPI-002":  {"The requested group does not exist.", ""},
	"RX-GRUPPI-003":  {"The requested user does not exist.", ""},
	"RX-OPENSSL-001": {"OpenSSL is older than 3.5: QUIC is missing.", ""},
	"RX-OPENSSL-002": {"The OpenSSL version could not be read.", ""},
	"RX-DESKTOP-001": {"This machine has no desktop supported by REMOTIX, and none was chosen for installation: REMOTIX is not installed.", "Answer yes to the desktop question (remotix-install approva --desktop gnome|kde|xfce|lxqt), or install one."},
	"RX-DESKTOP-002": {"No supported desktop is installed: before installing you will be asked which one to add (condition C-DESKTOP).", ""},

	"RX-COMPAT-001": {"This distribution is outside REMOTIX.", ""},
	"RX-COMPAT-002": {"This distribution is not in the catalogue: whether REMOTIX runs on it is unknown.", ""},
	"RX-COMPAT-003": {"Immutable distributions are postponed until after phase 17 (decision D9).", ""},
	"RX-COMPAT-004": {"This combination is waiting for a decision by the user.", ""},
	"RX-COMPAT-005": {"This desktop is not supported on this distribution.", ""},
	"RX-COMPAT-006": {"The desktop version is older than the minimum.", ""},
	"RX-COMPAT-007": {"The machine lacks an indispensable requirement.", ""},

	"RX-PIANO-001": {"The machine changed after the plan was made: the plan is no longer valid.", "Make the plan again on this machine (remotix-install piano)."},
	"RX-PIANO-002": {"The plan cannot be read or has an unknown format.", ""},
	"RX-PIANO-003": {"The plan was not approved: nothing is touched.", "Approve it with remotix-install approva, or with --approva."},
	"RX-PIANO-004": {"The plan contains a step this engine does not know.", ""},
	"RX-PIANO-005": {"The approval does not match this plan (the plan was changed afterwards).", "Approve the plan again."},

	"RX-STATO-001":     {"There is an unfinished operation: it must be resumed or rolled back first.", "remotix-install riprendi, or remotix-install annulla."},
	"RX-STATO-002":     {"Invalid state transition: this is an engine defect.", ""},
	"RX-STATO-003":     {"Another engine is working right now.", "Wait for it to finish."},
	"RX-STATO-004":     {"There is no operation to resume or roll back.", ""},
	"RX-STATO-005":     {"The operation is in a final state: it is neither resumed nor rolled back (to remove REMOTIX, uninstall).", ""},
	"RX-RIPRESA-001":   {"The machine changed during the operation: a step already done is gone or was changed by someone else.", "Look at the log; then resume or roll back."},
	"RX-RIPRESA-002":   {"The operation stopped before touching the machine: there is nothing to resume.", "Run remotix-install applica with the plan again."},
	"RX-RIPRESA-003":   {"The log ended with a half-written line (interruption): the line was removed.", ""},
	"RX-AZIONE-001":    {"An installation step failed: the operation is being rolled back.", ""},
	"RX-AZIONE-002":    {"A step could not be rolled back: the machine did not fully return to how it was.", "The exact list of what remains is in the certificate."},
	"RX-AZIONE-003":    {"A step's verification does not pass: the operation is being rolled back.", ""},
	"RX-AZIONE-004":    {"The plan contains a step this engine knows but cannot perform yet: stopping before touching the machine.", "The step arrives with phases 5-8 of the engine (T5)."},
	"RX-INST-001":      {"Installation not certified by the installer (no CONFIRMED remotix-install operation): stated for information only.", ""},
	"RX-INST-002":      {"After the update the machine check found problems.", "remotix-install verifica"},
	"RX-AZIONE-005":    {"An IRREVERSIBLE step cannot be rolled back.", ""},
	"RX-PACCHETTI-001": {"The package is not the plan's one (different sha256).", "Make the plan again with the right package."},
	"RX-PACCHETTI-002": {"Removing the REMOTIX packages would also remove someone else's package: nothing is touched.", "Check who depends on that package."},
	"RX-PACCHETTI-003": {"This family's package manager is not known to the engine.", ""},
	"RX-PACCHETTI-004": {"The package manager is half-way through an earlier transaction.", "Fix it with its own remedy (dpkg --configure -a, dnf, zypper verify) and retry."},
	"RX-PACCHETTI-005": {"The transaction could not be resolved or downloaded: nothing was installed.", "Check the network and the repositories, then resume."},
	"RX-CINTURA-001":   {"The switched-off safety-belt file is missing (the package did not bring it).", ""},
	"RX-SYSTEMD-002":   {"The unit is masked: the administrator switched it off on purpose.", ""},
	"RX-SYSTEMD-003":   {"The unit does not exist.", ""},
	"RX-FILE-001":      {"The file was changed by someone else during the operation: it is not touched.", ""},

	"RX-AGG-001": {"REMOTIX is at the latest version of its channel.", ""},
	"RX-AGG-002": {"A maintenance update is available (security or rebuild): it is applied automatically, as the configuration says.", ""},
	"RX-AGG-003": {"The new yearly version is available: it is not applied automatically, the administrator chooses it.", "remotix-install aggiorna --annuale"},
	"RX-AGG-004": {"An update is available, but the configuration says not to apply it automatically (notice only).", "remotix-install aggiorna --applica"},
	"RX-AGG-005": {"Automatic updates are switched off by the configuration.", ""},
	"RX-AGG-006": {"REMOTIX was not installed by the installer: there is nothing to update from here.", "Install with remotix-install."},
	"RX-AGG-007": {"The REMOTIX archive does not answer, or its signature does not verify (the package manager refuses it).", "Check the network; if the package manager talks about signatures, do NOT force it: the archive may have been altered."},
	"RX-AGG-008": {"On Arch the update would also touch packages that are not REMOTIX (a partial upgrade, which Arch does not support): it is not applied automatically.", "pacman -Syu, then remotix-install aggiorna"},
	"RX-AGG-009": {"The requested version is not in the REMOTIX archive.", "remotix-install aggiorna --controlla lists the versions available."},
	"RX-AGG-010": {"The update configuration cannot be read.", "Fix /etc/remotix/aggiornamenti.conf (remotix-install aggiorna --mostra)."},
}
