package motore

import (
	"fmt"
	"strings"
)

// TabellaVersioni generates from the catalogue the tables of §3.1 (the distributions, the ones out, the
// components' minimum versions). The catalogue is the SINGLE SOURCE: the technical manual is regenerated from
// here at every release, not copied by hand.
func TabellaVersioni(c *Catalogo) string {
	var b strings.Builder
	fmt.Fprintf(&b, "*Generated by remotix-install catalog --table, catalogue %s (sequence %d).*\n\n", c.Versione, c.Sequenza)
	fmt.Fprintf(&b, "**Distributions**\n\n| distribution | minimum version | status | desktops | conditions |\n|---|---|---|---|---|\n")
	for _, p := range c.Piattaforme {
		var desk, cond []string
		visti := map[string]bool{}
		metti := func(x string) {
			if !visti[x] {
				visti[x] = true
				cond = append(cond, x)
			}
		}
		if len(p.H264.SenzaH264DiSerie) > 0 {
			metti("H.264 on " + strings.Join(p.H264.SenzaH264DiSerie, " and ") + ": a VA-API driver with H.264, not in the distribution's packages")
		}
		for _, d := range p.Depositi {
			metti(nonVuoto(c.Depositi[d].Nome, d) + " enabled")
		}
		for _, d := range DESKTOP {
			dc, ok := p.Desktop[d]
			if !ok || !dc.Supportato {
				continue
			}
			desk = append(desk, NomeDesktop(d))
			for _, k := range dc.Componenti {
				if k == "labwc" {
					continue // the package for XFCE and LXQt always brings it: it is not a peculiarity
				}
				metti("`" + k + "` (" + NomeDesktop(d) + ")")
			}
			for _, k := range dc.Limiti {
				metti(k)
			}
			// on openSUSE the lxqt pattern brings the scalable font only as recommended (§11.1)
			if d == "lxqt" && dc.ServeCarattere && p.Famiglia == "suse" {
				metti("a scalable font for LXQt")
			}
		}
		if len(cond) == 0 {
			cond = []string{"—"}
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", p.Distribuzione, grassettoVersione(p.EtichettaVersione),
			statoPiattaforma(p), strings.Join(desk, ", "), strings.Join(cond, "; "))
	}
	for _, p := range c.Piattaforme {
		for _, d := range p.Derivate {
			v := d.VersioneMinima
			if v == "" {
				v = strings.Join(d.Versioni, ", ")
				if v == "*" {
					v = "rolling"
				}
			}
			nota := "as " + p.Distribuzione
			if d.Nota != "" {
				nota += "; " + d.Nota
			}
			fmt.Fprintf(&b, "| %s | %s | compatible, not certified | as %s | %s |\n", d.Nome, v, p.Nome, nota)
		}
	}
	fmt.Fprintf(&b, "\n**Excluded, and why**\n\n")
	for _, e := range c.Escluse {
		fmt.Fprintf(&b, "- %s %s: %s\n", e.ID, strings.Join(e.Versioni, ", "), e.Motivo)
	}
	for _, x := range c.FuoriSempre {
		fmt.Fprintf(&b, "- %s\n", x)
	}
	fmt.Fprintf(&b, "\n**Minimum component versions**\n\n| component | minimum | why |\n|---|---|---|\n")
	for _, k := range c.ComponentiMinimi {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", k.Componente, k.Minimo, k.Perche)
	}
	return b.String()
}

func grassettoVersione(s string) string {
	primo, resto, _ := strings.Cut(s, " ")
	if resto != "" {
		return "**" + primo + "** " + resto
	}
	return "**" + primo + "**"
}

func statoPiattaforma(p Piattaforma) string {
	switch {
	case p.Matrice && p.GiroIntero != "":
		return "certified (full run of " + p.GiroIntero + ")"
	case p.Matrice:
		return "in the matrix: certified at the full run (T10)"
	}
	return "analysed, outside the matrix"
}
