package motore

// testi: il catalogo dei testi del motore e della riga di comando, in inglese (DECISIONI §10.35).
// Le chiavi sono stabili; i %s e %d seguono fmt.Sprintf.
var testi = map[string]string{
	// stati (§6.6.2), come li dice l'avanzamento
	"state.NEW":                       "new",
	"state.TRUSTED":                   "trust checked",
	"state.EXAMINED":                  "machine examined",
	"state.ASSESSED":                  "compatibility assessed",
	"state.PLANNED":                   "plan checked",
	"state.APPROVED":                  "plan approved",
	"state.ACQUIRED":                  "everything needed is ready",
	"state.RUNNING":                   "applying the plan",
	"state.INTERRUPTED":               "found interrupted",
	"state.APPLIED":                   "plan applied",
	"state.VERIFYING":                 "verifying",
	"state.VERIFIED":                  "verified",
	"state.CONFIRMED":                 "CONFIRMED",
	"state.CONFIRMED_WITH_CONDITIONS": "CONFIRMED WITH CONDITIONS",
	"state.ROLLING_BACK":              "rolling back",
	"state.ROLLED_BACK":               "ROLLED BACK: the machine is as it was",
	"state.PARTIALLY_ROLLED_BACK":     "PARTLY ROLLED BACK",
	"state.BLOCKED":                   "BLOCKED",
	"state.REFUSED":                   "REFUSED: nothing was touched",
	"ev.rimedio":                      "remedy",
	"ev.si_riprende":                  "resuming",
	"ev.operazione":                   "operation %s",

	// compatibilità (§6.6.8)
	"comp.nella_matrice":   "in the matrix (%s)",
	"comp.fuori_matrice":   "analysed, outside the matrix (%s)",
	"comp.derivata":        "derivative of %s (compatible, not certified)",
	"comp.esclusa":         "excluded",
	"comp.sconosciuta":     "unknown",
	"cond.nvidia":          "NVIDIA with the proprietary driver and without its Vulkan driver (ICD): no encoding on this card, video is encoded by the other card",
	"cond.amd_senza_vaapi": "on %s Mesa has no VA-API: the AMD card does not encode, video is encoded by the other card",
	"pacchetti.trattenuti": "the new packages are gone, except those kept because something that stays needs them: %s",
	"pacchetti.chiesto_da": "needed by %s",
	"cond.3d":              "%s requires the card's 3D acceleration: %s",
	"mot.3d":               "%s requires 3D acceleration, and the machine has no card (no render node): %s",
	"inc.openssl":          "OpenSSL version",
	"inc.desktop":          "desktop %s",
	"inc.h264":             "H.264 on the card (%s)",

	// il piano di prova e i passi (§6.6.4)
	"np.utente": "no user given (--users): there is no «video» group step",

	"az.file":              "write %s",
	"az.file.fa":           "the existing file (if any) is saved, the new one is written to «%s» next to it, fsync, and renamed over it",
	"az.file.verifica":     "file sha256 and permissions equal to the plan's",
	"az.file.annulla":      "the saved file is put back (or removed, if it was not there), and created directories if left empty",
	"az.gruppo":            "add %s to the %s group",
	"az.gruppo.fa":         "gpasswd -a %s %s (unless already there: then nothing, recorded as PRE-EXISTING)",
	"az.gruppo.verifica":   "%s among the members of %s",
	"az.gruppo.annulla":    "gpasswd -d %s %s, only if REMOTIX added them",
	"az.unita":             "enable the unit %s",
	"az.unita.fa":          "EnableUnitFiles %s on systemd's D-Bus (without starting it)",
	"az.unita.verifica":    "unit file state of %s = enabled",
	"az.unita.annulla":     "DisableUnitFiles %s, if it was not enabled before",
	"az.servizio":          "enable and start remotix.service",
	"az.servizio.fa":       "EnableUnitFiles and StartUnit of remotix.service, after the checks with the service stopped (7a)",
	"az.servizio.verifica": "active, the port answers on TCP and UDP (7b)",
	"az.servizio.annulla":  "StopUnit and DisableUnitFiles of remotix.service",

	"az.pacchetti":            "have the distribution's package manager install %s",
	"az.pacchetti.fa":         "the transaction is resolved, everything downloaded and verified (resolved set in the log), then the manager installs from the cache, offline",
	"az.pacchetti.verifica":   "every package of the resolved set installed at its version, manager not half-way",
	"az.pacchetti.annulla":    "the manager removes the NEW packages, and only those (simulating first); upgraded ones stay and are declared",
	"az.sessioni":             "close the REMOTIX sessions still open (%d: %s)",
	"az.sessioni.fa":          "logind TerminateSession on the sessions with PAM service «remotix» only: the same people's local or ssh sessions stay",
	"az.sessioni.verifica":    "none of those sessions is still open",
	"az.sessioni.annulla":     "IRREVERSIBLE: unsaved work is lost, sessions do not reopen",
	"az.disfa":                "undo: %s",
	"az.disfa.verifica":       "as it was before the installation",
	"np.nessun_gruppo":        "no card node with a group: nobody to add",
	"np.gruppi":               "the people of this machine are added to the graphics card groups (%s), and so is everyone who logs in to REMOTIX for the first time: without them a remote desktop cannot use the card",
	"np.firewall":             "the firewall (%s) is on: port %s TCP and UDP must be reachable from the other machines — opening it is up to the administrator",
	"np.sospensione":          "REMOTIX does not change how this machine suspends or powers off: a machine that suspends when idle disconnects everyone",
	"manca.carattere":         "a scalable font (labwc does not start without one)",
	"manca.desktop":           "GNOME %s or newer, KDE Plasma %s or newer, XFCE %s or newer (Wayland), LXQt %s or newer",
	"cond.codifica_ignota":    "H.264 encoding on the card was not tested by REMOTIX (%s): it is not confirmed",
	"ver.nessuna_scheda":      "no card can encode: the card's encoder does not open (%s)",
	"az.iscrizione":           "remove %s from the %s group (added by REMOTIX at first connection)",
	"az.iscrizione.fa":        "gpasswd -d, if still in the group",
	"az.iscrizione.verifica":  "no longer in the group",
	"az.iscrizione.annulla":   "gpasswd -a (added back)",
	"az.registri":             "remove the REMOTIX session log (%s) from every user's home — now: %s",
	"az.registri.fa":          "only sessione.log is removed, and the %s folder if left empty; nothing else in the homes",
	"az.registri.verifica":    "none of those files is left",
	"az.registri.annulla":     "put back byte for byte, with permissions and owner (copies in the operation folder)",
	"az.registri.dichiarata":  "uninstalling removes ~/.local/state/remotix/sessione.log from every home (and the folder if left empty) — %s",
	"az.registri.nessuno":     "no session log in any home",
	"az.registri.tolti":       "removed: %s",
	"az.registri.ancora":      "still in the homes: %s",
	"az.registri.non_rimesso": "not back as it was",
	"az.registri.rimessi":     "the session logs are back",
	"ver.pam":                 "the REMOTIX login stack resolves (files, includes, modules)",
	"ver.porta":               "the firewall lets port %s TCP and UDP through",
	"ver.porta_nessuno":       "no firewall on",
	"cond.pam_ignota":         "the login stack could not be checked (%s)",
	"cond.porta_ignota":       "unknown whether the firewall lets port %s through: check by hand",
	"cond.porta_chiusa":       "the firewall closes %s: REMOTIX cannot be reached from outside until it is opened (D6)",
	"cli.certifica":           "Certification of installation %s: %s",
	"ver.codifica_assente":    "the REMOTIX encoding test gave no readable answer",

	// operazione e certificato
	"op.chiesto":          "requested by the administrator",
	"cert.titolo":         "REMOTIX — certificate of operation %s",
	"cert.stato":          "final state",
	"cert.mestiere":       "job",
	"cert.motore":         "engine",
	"cert.catalogo":       "catalogue",
	"cert.fiducia":        "trust",
	"cert.piano":          "plan",
	"cert.impronta":       "fingerprint",
	"cert.controlli":      "checks",
	"cert.condizioni":     "conditions",
	"cert.nessuna":        "none",
	"cert.non_annullato":  "NOT ROLLED BACK",
	"cert.prodotto_prova": "none: engine test plan (T4)",
	"cert.fiducia_no":     "the catalogue could NOT be used: the operation stopped at phase 0",

	// riga di comando
	"cli.uso": `remotix-install — the REMOTIX installation engine (version %s, format %s)

REMOTIX comes as one file: sudo sh remotix-VERSION.run   (it runs «install»; «check» and «tui» too)
REMOTIX does not change the system: what is missing is said, and providing it is up to the administrator.

  remotix-install check     [--port N] [--json]
        examines the machine WITHOUT TOUCHING ANYTHING: what REMOTIX can do on it, and what is missing
  remotix-install install   [--port N] [--users A,B]
        shows the plan with the exact packages, asks «Proceed? [y/N]», installs and verifies.
        On a machine that already has REMOTIX it is the upgrade to the .run's version.
        An unfinished operation is rolled back first (never a system left half way)
  remotix-install uninstall [--purge]     shows the plan, asks, removes REMOTIX (--purge: also the configuration)
  remotix-install status    [--json]      the operations, and the installation checks run again (GREEN, CONDITIONAL, RED)
  remotix-install tui       [--port N]    the same, in a text interface (ssh, console)

  common options: --state-dir DIR (default /var/lib/remotix/operations), --catalog FILE (given by hand)
`,
	"cli.titolo":             "REMOTIX — machine check (read only: nothing was touched)",
	"cli.distribuzione":      "Distribution",
	"cli.desktop":            "The desktops:",
	"cli.non_installato":     "not installed",
	"cli.non_si_sa":          "unknown whether present",
	"cli.installato":         "installed (%s)",
	"cli.perche":             "why",
	"cli.condizione":         "condition",
	"cli.nota":               "note",
	"cli.incognite":          "What could NOT be found out (it does not count as «fine»):",
	"cli.avvisi":             "Warnings and problems:",
	"cli.fatti":              "The facts (DETECTED = seen; VERIFIED = actually tested; UNKNOWN = unknown):",
	"cli.non_fatto":          "not done: %s %s %s",
	"cli.dichiarato":         "always done: %s",
	"cli.router":             "From outside the local network: forward port %d, TCP and UDP, on the router to this machine (REMOTIX does not do it by itself: no UPnP).",
	"cli.operazione":         "operation %s: %s",
	"cli.nessuna_op":         "no operation in %s",
	"cli.certificata":        "installation certified by the installer: operation %s %s",
	"cli.fiducia":            "Trust: catalogue %s, sequence %d — %s",
	"cli.versioni_annotate":  "REMOTIX versions recorded: %s",
	"fid.pacchetto":          "the catalogue of the installed remotix-install package",
	"fid.scaricato":          "the catalogue of the engine %s (from the REMOTIX .run file, whose sha256 is published)",
	"fid.a_mano":             "the catalogue given by hand: %s (the administrator's)",
	"cli.aperta":             "  ← open: remotix-install install rolls it back",
	"cli.mancano":            "MISSING — REMOTIX does not install it: providing it is up to the administrator:",
	"cli.root":               "run as administrator (root): sudo",
	"cli.aperta_annulla":     "An unfinished operation was found (%s): it is rolled back first, so the system is never left half way.",
	"cli.aperta_disinstalla": "An unfinished uninstallation was found (%s): it is completed first.",
	"cli.bloccato":           "REMOTIX is not installed: nothing was touched. Run it again when what is missing is there.",
	"cli.gia_installato":     "REMOTIX %s is already installed: nothing to do.",
	"cli.procedo":            "Proceed?",
	"cli.procedo_togli":      "Remove REMOTIX?",
	"cli.niente_toccato":     "Nothing was touched.",
	"cli.piano":              "The plan (%s, %s):",
	"cli.pacchetti":          "What the package manager will do (its own simulation):",
	"cli.non_installato_ora": "REMOTIX is not installed by the installer on this machine.",
	"cli.catalogo_info":      "catalogue %s (sequence %d), issued on %s, minimum engine %s\ndigest %s\n%s\n",
}
